package org.neteinstein.instamaps

import android.app.Application
import org.koin.android.ext.koin.androidContext
import org.koin.android.ext.koin.androidLogger
import org.koin.core.context.startKoin
import org.neteinstein.instamaps.core.common.di.commonModule
import org.neteinstein.instamaps.feature.geocoding.di.geocodingModule
import org.neteinstein.instamaps.feature.maps.di.mapsModule
import org.neteinstein.instamaps.feature.share.di.shareModule
import org.neteinstein.instamaps.feature.videoprocessing.di.videoProcessingModule

/**
 * Composition root: starts Koin once, wiring every feature/core module's DI graph together.
 * [BuildConfig.PLACES_API_KEY] is generated by the secrets-gradle-plugin from `secrets.properties`
 * (gitignored, developer-local) or `local.defaults.properties` (committed placeholder) - see
 * app/build.gradle.kts and the README for setup instructions.
 */
class InstaMapsApplication : Application() {
    override fun onCreate() {
        super.onCreate()
        startKoin {
            androidLogger()
            androidContext(this@InstaMapsApplication)
            modules(
                commonModule,
                mapsModule,
                geocodingModule(BuildConfig.PLACES_API_KEY),
                videoProcessingModule,
                shareModule,
            )
        }
    }
}
